export const WELLNESS_TEST_COPY = {
  "metaTitle": "Wellness Test - Understand Your Mind & Live a Healthier Life | StrongBody AI",
  "metaDescription": "Take free wellness tests to understand your mental and physical health. Get AI-powered insights and connect with verified global experts.",
  "eyebrow": "StrongBody AI assessment",
  "heroTitle": "Wellness Test",
  "heroLead": "Science-backed wellness tests help you understand your mental and physical health with clearer next steps.",
  "heroCta": "Explore tests",
  "howTitle": "How it works",
  "howLead": "Answer simple questions, submit your test, and review personalized insights.",
  "step1Title": "Choose a test",
  "step1Text": "Pick the wellness area you want to understand today.",
  "step2Title": "Answer honestly",
  "step2Text": "Move through short questions designed around practical wellbeing signals.",
  "step3Title": "Review insights",
  "step3Text": "See your result and continue with StrongBody AI support.",
  "testsTitle": "Available wellness tests",
  "testsLead": "Choose from the assessments currently available for this site.",
  "noTests": "No wellness tests are available yet.",
  "questions": "questions",
  "minutes": "minutes",
  "start": "Start now",
  "view": "View test",
  "back": "Back",
  "next": "Next",
  "finish": "Finish",
  "saving": "Saving...",
  "questionOf": "Question {current} of {total}",
  "loading": "Preparing your test...",
  "analyzingTitle": "Analyzing your test data",
  "analyzingText": "Your answers are being calculated with StrongBody AI insights.",
  "finishing": "Finishing up...",
  "secure": "Your test data is kept secure.",
  "missingAnswers": "No saved test answers found. Please retake the test.",
  "submitError": "Unable to submit your test. Please try again.",
  "resultTitle": "Your wellness result",
  "insight": "Insight",
  "level": "Level",
  "score": "Score",
  "retake": "Retake this test",
  "notFound": "Test not found",
  "readyPrompt": "Ready to start with confidence?"
} as const;
